#!/usr/bin/env zsh

# Disclaimer: Generated by AI so I can focus on the project itself

set -euo pipefail

readonly BASELINE="ffa0979bb2f6eb49df2a58a4422e39cc08ec0016"
readonly CURRENT="${1:-HEAD}"

# Source-ish extensions for LOC counting (skip binary, images, etc.)
readonly LOC_PATTERN='\.(c|h|el|m|in|ac|am|mk|sh|py|pl|rb|texi|texinfo|org|txt|md|json|xml|html|css|js|rs|awk|sed|sub)$|/(Makefile|README|INSTALL|ChangeLog|NEWS|CONTRIBUTE|configure)$'

# ── helpers ──────────────────────────────────────────────────────────

bytes_at() {
  git ls-tree -r -l "$1" | awk '{s += $4} END {print s + 0}'
}

files_at() {
  git ls-tree -r --name-only "$1" | wc -l | tr -d ' '
}

loc_at() {
  # List tracked text files, batch-cat via git show, count lines.
  # Uses xargs -0 for robustness with whitespace in paths.
  git ls-tree -r --name-only "$1" \
    | grep -iE "$LOC_PATTERN" \
    | sed "s|^|$1:|" \
    | tr '\n' '\0' \
    | xargs -0 git show 2>/dev/null \
    | wc -l \
    | tr -d ' '
}

# Format bytes as MB (2 decimal places)
as_mb() {
  awk "BEGIN {printf \"%.2f\", $1 / 1048576}"
}

# Format a delta with percentage
fmt_row() {
  local label=$1 base=$2 curr=$3 unit=${4:-""}
  local delta=$(( curr - base ))
  local pct
  if (( base != 0 )); then
    pct=$(awk "BEGIN {printf \"%.1f\", ($delta / $base) * 100}")
  else
    pct="n/a"
  fi

  local sign=""
  (( delta > 0 )) && sign="+"

  if [[ -n $unit ]]; then
    printf "  %-14s %10s %-3s → %10s %-3s  %s%s %s (%s%%)\n" \
      "$label" "$base" "$unit" "$curr" "$unit" "$sign" "$delta" "$unit" "$pct"
  else
    printf "  %-14s %10s     → %10s       %s%s (%s%%)\n" \
      "$label" "$base" "$curr" "$sign" "$delta" "$pct"
  fi
}

# ── resolve refs ─────────────────────────────────────────────────────

if ! git rev-parse --git-dir &>/dev/null; then
  echo "error: not inside a git repository" >&2
  exit 1
fi

base_short=$(git rev-parse --short "$BASELINE" 2>/dev/null) || {
  echo "error: baseline commit not found: $BASELINE" >&2; exit 1
}
curr_short=$(git rev-parse --short "$CURRENT" 2>/dev/null) || {
  echo "error: target ref not found: $CURRENT" >&2; exit 1
}
curr_subject=$(git log -1 --format=%s "$CURRENT" 2>/dev/null)

# ── collect metrics ──────────────────────────────────────────────────

echo "µmacs reduction report"
echo "  baseline  $base_short"
echo "  current   $curr_short  $curr_subject"
echo ""

echo -n "  gathering baseline..."
base_bytes=$(bytes_at "$BASELINE")
base_files=$(files_at "$BASELINE")
base_loc=$(loc_at "$BASELINE")
echo " done"

echo -n "  gathering current... "
curr_bytes=$(bytes_at "$CURRENT")
curr_files=$(files_at "$CURRENT")
curr_loc=$(loc_at "$CURRENT")
echo " done"

echo ""

# ── size in MB ───────────────────────────────────────────────────────

base_mb=$(as_mb $base_bytes)
curr_mb=$(as_mb $curr_bytes)
diff_bytes=$(( curr_bytes - base_bytes ))

# awk handles negative values fine for the delta
diff_mb=$(awk "BEGIN {printf \"%.2f\", $diff_bytes / 1048576}")
size_pct=$(awk "BEGIN {printf \"%.1f\", ($diff_bytes / $base_bytes) * 100}")

sign=""
(( diff_bytes > 0 )) && sign="+"

printf "  %-14s %10s MB  → %10s MB   %s%s MB (%s%%)\n" \
  "Size" "$base_mb" "$curr_mb" "$sign" "$diff_mb" "$size_pct"

fmt_row "Files" "$base_files" "$curr_files"
fmt_row "LOC (source)" "$base_loc" "$curr_loc"

echo ""
echo "  LOC covers: *.{c,h,el,m,in,ac,am,mk,sh,py,pl,texi,...}"
